### ISSUE TITLE
Add golangci-lint support

### ISSUE THREAD

**Issue by benner** [Barzahlen/pronto-golang#5]
It's lot faster and can be used alone instead multiple separate linters.

URL: https://github.com/golangci/golangci-lint

**Comment by tobischo** [comment]
Looks interesting at first glance.
Analyzing whether it makes sense to add this or not might take some time though.
Feel free to provide more information or a pull request (which adds this as an additional tool which may be enabled or not for usage).

**Comment by tobischo** [comment]
Thank you for the contribution

Resolved through #6 / #7
