### ISSUE TITLE
command(file_path) Not working

### ISSUE THREAD

**Issue by GabKlein** [Barzahlen/pronto-golang#8]
Hello,

Thank you for this gem that I'm testing. I found an issue regarding the file_path pass to the tools. Can you change this method https://github.com/Barzahlen/pronto-golang/blob/master/lib/pronto/golang/tools/base.rb#L16 to look like :

```
def command(file_path)
   "#{base_command} #{parameters} #{file_path}"
end
```

**Comment by tobischo** [comment]
Interesting, I am not sure why this was that way 🤔 
It would definitely require looking into this more throughly to ensure that all currently supported tools properly support this.
I am not sure when I'll get around to doing that.
If you could prepare a pull request for it, that might speed things up if you urgently require this change

**Comment by GabKlein** [comment]
Hello, I created a PR https://github.com/Barzahlen/pronto-golang/pull/9
Can you take a look at it?

**Comment by tobischo** [comment]
Applied in https://github.com/Barzahlen/pronto-golang/commit/fc6239237ceecba0bd8f4f6d1c9fa2dad7e84021

Please let me know if everything works for you

**Comment by tobischo** [comment]
I will consider this as closed for now.
